name: Create Pull Request

on:
  push:
    branches:
      - staging  # Déclenche le workflow lorsque des commits sont poussés sur la branche staging

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Make changes to pull request here

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Merge staging into main"
          title: "Merge staging into main"
          labels: "automerge"
          branch: "main"
