name: Merge Staging to Main

on:
  push:
    branches:
      - staging

jobs:
  merge_to_main:
    name: Merge to Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge staging into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/staging --no-ff --no-edit
          git push origin main









